
COURSES_DICT = {

'cs101': 'Introduction to Computer Science',
'PH100': 'Intro to Physics: Landmarks in Physics',
'ST101': 'Intro to Statistics: Making Decisions Based on Data',
'cs215': 'Algorithms: Crunching Social Networks',
'cs222': 'Differential Equations in Action',
'cs253': 'Web Development',
'cs255': 'HTML5 Game Development',
'cs258': 'Software Testing',
'cs259': 'Software Debugging',
'cs262': 'Programming Languages',
'cs271': 'Introduction to Artificial Intelligence',
'cs291': 'Interactive Rendering',
'cs313': 'Introduction to Theoretical Computer Science',
'ep245': 'How to Build a Startup',
'cs212': 'Design of Computer Programs',
'cs344': 'Introduction to Parallel Programming',
'cs348': 'Functional Hardware Verification',
'cs373': 'Artificial Intelligence for Robotics',
'cs387': 'Applied Cryptography',
'ma006': 'Visualizing Algebra',
'ma008': 'College Algebra',
'ud436': 'Computer Networking - Open',
'UD015': 'Object-Oriented JavaScript',
'UD032': 'Data Wrangling with MongoDB',
'UD036': 'Programming Foundations with Python',
'UD088': 'Full Stack Foundations',
'UD110': 'Intro to AJAX',
'UD120': 'Intro to Machine Learning',
'UD162': 'Intro to Point and Click App development',
'UD197': 'Intro to Relational Databases',
'UD201': 'Intro to Inferential Statistics',
'UD245': 'Intro to jQuery',
'UD292': 'HTML5 Canvas',
'UD304': 'Intro to HTML and CSS',
'UD359': 'Intro to Data Science',
'UD381': 'Real-Time Analytics with Apache Storm',
'UD436': 'Computer Networking - Open',
'UD507': 'Data Visualization and D3.js',
'UD585': 'Intro to iOS App Development with Swift',
'UD617': 'Intro to Hadoop and MapReduce',
'UD651': 'Data Analysis with R',
'UD675': 'Machine Learning: Supervised Learning',
'UD741': 'Machine Learning: Unsupervised Learning',
'UD775': 'How to Use Git and GitHub',
'UD804': 'JavaScript Basics',
'UD805': 'Software Development Processes - Open',
'UD820': 'Machine Learning: Reinforcement Learning',
'UD827': 'Intro to Descriptive Statistics',
'UD849': 'UX Design for Mobile Developers',
'UD853': 'Developing Android Apps',
'UD859': 'Developing Scalable Apps with Java',
'UD884': 'Website Performance Optimization',
'UD893': 'Responsive Web Design Fundamentals',
'UD919': 'Model Building and Validation',
'UD989': 'JavaScript Design Patterns',
'CS046': 'Introduction to Programming in Java: Learning Java',
'CS101': 'Intro to Computer Science: Building a Search Engine',
'CS212': 'Design of Computer Programs: Programming Principles',
'CS215': 'Algorithms: Crunching Social Networks',
'CS222': 'Differential Equations: Making Math Matter',
'CS253': 'Web Application Engineering: How to Build a Blog',
'CS255': 'HTML5 Game Development: Building High Performance Web Applications',
'CS256': 'Mobile Web Development',
'CS258': 'Software Testing: How to Make Software Fail',
'CS259': 'Software Debugging: Automating the Boring Tasks',
'CS262': 'Programming Languages: Building a Web Browser',
'CS271': 'Introduction to Artificial Intelligence: AI Class',
'CS291': 'Interactive 3D Graphics: Creating Virtual Worlds',
'CS313': 'Introduction to Theoretical Computer Science',
'CS344': 'Intro To Parallel Programming: Using CUDA to Harness the Power of GPUs',
'CS348': 'Functional Hardware Verification: How to Verify Chips and Eliminate Bugs',
'CS373': 'Artificial Intelligence for Robotics: Programming a Robotic Car',
'CS387': 'Applied Cryptography: The Science of Secrets',
'DESIGN101': 'Intro to the Design of Everyday Things',
'EP245': 'How to Build a Startup: The Lean LaunchPad',
'MA004': 'Introductory Algebra Review',
'MA006': 'Visualizing Algebra: Problems and Patterns',
'MA008': 'College Algebra: Animals, Architecture, and Innovation',
'PS001': 'Introduction to Psychology: The Science of Thought and Behavior',
'ST095': 'Statistics: The Science of Decisions',


}